[project]
name = "gcp-incidents"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "google-cloud-firestore==2.21.0",
    "requests==2.32.5",
    "Flask==3.1.2",
    "threader==0.1.1",
    "tqdm==4.67.1",
    "tweepy==4.14.0"
]
